/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers'
import type { Provider } from '@ethersproject/providers'
import type {
	ISemaphoreVerifier,
	ISemaphoreVerifierInterface,
} from '../../../../@semaphore-protocol/contracts/interfaces/ISemaphoreVerifier'

const _abi = [
	{
		inputs: [
			{
				internalType: 'uint256',
				name: 'merkleTreeRoot',
				type: 'uint256',
			},
			{
				internalType: 'uint256',
				name: 'nullifierHash',
				type: 'uint256',
			},
			{
				internalType: 'uint256',
				name: 'signal',
				type: 'uint256',
			},
			{
				internalType: 'uint256',
				name: 'externalNullifier',
				type: 'uint256',
			},
			{
				internalType: 'uint256[8]',
				name: 'proof',
				type: 'uint256[8]',
			},
			{
				internalType: 'uint256',
				name: 'merkleTreeDepth',
				type: 'uint256',
			},
		],
		name: 'verifyProof',
		outputs: [],
		stateMutability: 'view',
		type: 'function',
	},
] as const

export class ISemaphoreVerifier__factory {
	static readonly abi = _abi
	static createInterface(): ISemaphoreVerifierInterface {
		return new utils.Interface(_abi) as ISemaphoreVerifierInterface
	}
	static connect(address: string, signerOrProvider: Signer | Provider): ISemaphoreVerifier {
		return new Contract(address, _abi, signerOrProvider) as ISemaphoreVerifier
	}
}
