import {
	PUBLIC_PROVIDER,
	PUBLIC_GROUP_ID,
	PUBLIC_GLOBAL_ANONYMOUS_FEED_ADDRESS,
	PUBLIC_TARGET_CHAIN_ID,
} from '$env/static/public'

export const GLOBAL_ANONYMOUS_FEED_ADDRESS = PUBLIC_GLOBAL_ANONYMOUS_FEED_ADDRESS
export const GROUP_ID = PUBLIC_GROUP_ID
export const PROVIDER = PUBLIC_PROVIDER
export const TARGET_CHAIN_ID = PUBLIC_TARGET_CHAIN_ID
