/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GlobalAnonymousFeed } from "./GlobalAnonymousFeed";
export * as factories from "./factories";
export { GlobalAnonymousFeed__factory } from "./factories/GlobalAnonymousFeed__factory";
