/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ISemaphore } from "./ISemaphore";
export type { ISemaphoreGroups } from "./ISemaphoreGroups";
export type { ISemaphoreVerifier } from "./ISemaphoreVerifier";
